### ISSUE TITLE
allowing to show metadata/jsdocs style comments for css variables

### ISSUE THREAD

**Issue by anoopsinghbayes** [willofindie/vscode-cssvar#100]
I was looking to see if this kind of feature is possible
right now what we get on hover of the variable is the actual value defined which is neat
what if we could define some meta data in the comments just above the variable to be shown when some hovered over the usage

example
```css
:root{
/***
* @description This is primary color for X Design system
*/
--primary-default:#157eba
}
```

and is some other css file
```css
.button-primary {
background-color:var(--primary-default);/*when you hover over the variable you see the description defined above*/
}
