### ISSUE TITLE
[Feat] Provide color values for deeply nested css variables

### ISSUE THREAD

**Issue by phoenisx** [willofindie/vscode-cssvar#104]
**Is your feature request related to a problem? Please describe.**
Example CSS file:

```css

* {
  --brand-hue: 0;

  --brand-dark1: hsl(var(--brand-hue), 0, 20%);
  --brand-dark2: hsl(var(--brand-hue), 0, 10%);

  --brand-light1: hsl(var(--brand-hue), 0, 90%);
  --brand-light2: hsl(var(--brand-hue), 0, 80%);
}

[color-scheme="light"] {
  --brand: var(--brand-light1);
  --brand-dark: var(--brand-light2);
}


[color-scheme="dark"] {
  --brand: var(--brand-dark1);
  --brand-dark: var(--brand-dark2);
}
```

**Describe the solution you'd like**
Color for `--brand` CSS property is not getting parsed.

| Current | Expected |
|-|-|
| <img width="100%" alt="image" src="https://user-images.githubusercontent.com/11786283/223181267-e31a4dce-9d08-4fe3-897c-17b16ee3dbb4.png"> | <img width="100%" alt="image" src="https://user-images.githubusercontent.com/11786283/223181733-6d815d77-1c9b-44ab-853d-22fd9c38b367.png"> |
