### ISSUE TITLE
[Feat] VSCode suggestion if try to re-define css variable

### ISSUE THREAD

**Issue by Yegorich555** [willofindie/vscode-cssvar#112]
One of the important feature of css-vars is ability to re-define value of existed css variable.  Lets assume I need to rewrite `--base-bg: #fff;`
 So when I type `--` I'm expecting to see list of vars
```css
button {
   --base-bg: #fff;
   background: var(--base-bg); /* intellisense suggests css-var here - it worksF */
}
.customButton {
   --base-bg: #efefefe; /* when I type  --b  intellisense-list is empty; but expected the same behavior as above */
}
```
