### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ennio-tomas** [willofindie/vscode-cssvar#6]
Inside Test.com folder I have:

.vscode/settings.json
`{
  "cssvar.extensions": [
    "css",
    "scss",
    "sass",
    "less"
  ],
  "cssvar.files": [
    "css/variables.less"
  ]
}`

Inside css/variables.less:
`:root {
  --textColor: #000000;
}`

and when I try in css/style.less file white:
`.test {
  background: --te
}`

where is no autocompletion for --textColor variable. What I am doing wrong? Thanks

**Comment by phoenisx** [comment]
Please check https://github.com/willofindie/vscode-cssvar#issues.

`Less`/ `Sass` pre-processors are not officially supported. They will work, only if they have plain CSS compatible styles.

For eg. Following won't work!!

```less
:root {
  --red: #f00;
}

.p1 {
   color: var(--red);
}

.p2 {
   background : #64d9c0;
   .p1(); // Mixin is being used
}

.p3 {
   background : #LESS520;
  .p1;
}
```

### But

Following will work.

```css
:root {
  --red: #f00;
}

.p1 {
   color: var(--red);
}

.p2 {
   background: #64d9c0;
   color: var(--red);
}

.p3 {
   background: #LESS520;
   color: var(--red);
}
```


I would suggest you create a separate `.less` file for your variables, that is a compatible CSS or Postcss file.

Let me know, if this resolves your issues 👍🏾
