### ISSUE TITLE
[Feat] Syntax highlighting for CSS variables that cannot be found

### ISSUE THREAD

**Issue by jjenzz** [willofindie/vscode-cssvar#73]
it would be great if the extension added error syntax highlighting to any lines referencing a CSS var that doesn't exist and listed them in the vscode problems tab, to aid refactoring. that is one of the only benefits of css-in-js that i miss while using this extension.

thanks for your continued work on this, really enjoying playing with it.

**Comment by phoenisx** [comment]
Hi @jjenzz 

Thanks for raising this request, and for your support 🙇🏽.
I will try to add this feature in v2.3.0. 💯

**Comment by phoenisx** [comment]
Hi @jjenzz 

This will be released in 2.3.0

Also do keep a note of the following while using this feature:

---

Since CSS variables are global in nature by default and can be used even without them being declared, an ideal CSS linter for CSS variables might not exist.
This feature enables strict checks for undeclared variables, thus variables which are undeclared or dynamically created will be considered as lint warn/errors.

**_For e.g. all the following CSS examples are valid:_**

```css
body {
  /* The following `--undeclared` variable does not exist */
  /* but its usage is completely valid, even though this extension */
  /* shows it as an error after enabling this feature */
  color: var(--undeclared, #333);
}
```

- In the following example variable is declared dynamically in CSS-in-JS

```js
// source.js
const foo = (index, value) => (
  css`
    --color-${index}: ${value};
  `
);
```

```css
/* index.css */
body {
  color: var(--color-1);
}
```

To fix the above cases, you can pass a list of variable names in the extension settings to ignore them, as follows:

```jsonc
// settings.json
{
  "cssvar.mode": ["warn", {
    "ignore": [
      "^--undeclared",
      "--color-\\w+?"
    ]
  }]
}
```

For details check the [examples folder](https://github.com/willofindie/vscode-cssvar/blob/main/examples/safe-parser/.vscode/settings.json)
