### ISSUE TITLE
[Feat] CSS variable scoping

### ISSUE THREAD

**Issue by jjenzz** [willofindie/vscode-cssvar#79]
currently if i do the following, intellisense will still list the `--color` var as an option in `.two` and will not error if used:

```css
.one {
  --color: red;
}

.two {
  color: var(--color);
}
```

this got me thinking. if a "prefix" was defined in the extension settings to denote "private variable" would the extension be able to filter things? for example:

```jsx
"cssvar.scopePrefix: "_", // would be underscore by default
```

then:

```css
.one {
  --_color: red;
}

/* typing `--` here will not list vars containing underscore prefix unless they are declared within `.two` */
.two {
  color: var(--_color);
}
```
