### ISSUE TITLE
[Bug] Populating Variable Values: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by adamtomat** [willofindie/vscode-cssvar#95]
**Describe the bug**
Plugin gives the following error:

```
Populating Variable Values: RangeError: Maximum call stack size exceeded
```

The CSS I am using is valid CSS and browsers behave the way I am intending. However, this plugin seems to get stuck in a recursion loop when trying to work out the value.

**To Reproduce**
I am using the following CSS:

```css
:root {
    --foo: #f00;
    --bar: var(--foo);
}

.test {
    background: var(--foo);
}

.test--two {
    --foo: var(--bar);
}
```

Using this gives me the described error. The intent here is that I can set `--bar` to match `--foo` by default, but I may choose to override it later (e.g. using a media query).

For example, here I am saying `--bar` behaves the same as `--foo` on mobile, but on tablet it behaves differently.

```css
:root {
    --foo: #f00;
    --bar: var(--foo);
}

@media (min-width: 768px) {
    :root {
        --bar: #0f0;
    }
}

.test {
    background: var(--foo);
}

.test--two {
    --foo: var(--bar);
}
```

When the media-query is added in, this plugin **does not** throw the error. It's able to resolve a value of `--bar` rather than getting stuck in a loop.

**Expected behavior**
That's a good question. I can see why this throwing an error. I'd probably expect `--foo` to resolve its value in the plugin to `#f00` and `--bar` to resolve its value to `var(--foo)` or even `#f00`. 

Or, it ignores these values and just shows `unknown` as the value rather than erroring.

**Details (please complete the following information):**
 - OS: macOS Monterey (v12.6)
 - VSCode version: Version: 1.73.0
 - Extension version: v2.4.1

**Additional context**
Some context as to _why_ we are doing this might be useful. We are building a large design-system for a site-builder. We have a large variables file that define things like this:

```css
:root {
    --card-background: #fff;
    --card-padding: 24px;

    --card-large-background: var(--card-background);
    --card-large-padding: var(--card-padding);
}

@media (min-width: 768px) {
    :root {
        --card-large-padding: 48px;
    }
}
```

Then in our card file we do something like this (basically just abstracting away the actual implementation to a set of variables that can be configured):

```css
.card {
    background: var(--card-background);
    padding: var(--card-padding);
}

/* Just updating variables instead of having to re-define each property */
.card--large {
    --card-background: var(--card-large-background);
    --card-padding: var(--card-large-padding);
}
```

This allows us to say:
> the large card is exactly the same as the normal card on mobile - but is larger on desktop

But someone can change that behaviour easily on a site by just updating the `--card-large-*` config.

The above would cause the plugin to error because we haven't changed `--card-large-background`.
